language: r
cache: packages
r_packages:
  - covr
addons:
  apt:
    packages:
      - libv8-dev
r_github_packages:
  - r-lib/covr
  - mrc-ide/cinterpolate
  - richfitz/dde
  - ropensci/jsonvalidate@use-ajv
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
